# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os.path

from PyQt5.QtWidgets import QFileDialog


class video_player_window(object):
    def __init__(self, parent=None):
        super(video_player_window, self).__init__(parent)

class Ui_MainWindow(object):
    video_path = ""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(342, 88)
        MainWindow.setFixedSize(342, 88)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 29, 321, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.load_video_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.load_video_button.setObjectName("load_video_button")
        self.load_video_button.clicked.connect(self.open_dialog_box)
        self.horizontalLayout.addWidget(self.load_video_button)

        self.process_file_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.process_file_button.setObjectName("process_file_button")
        self.process_file_button.setDisabled(True)
        self.process_file_button.clicked.connect(self.print_path)
        self.horizontalLayout.addWidget(self.process_file_button)

        self.play_video = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.play_video.setObjectName("play_video")
        self.play_video.setDisabled(True)
        self.play_video.clicked.connect(self.start_video_player)
        self.horizontalLayout.addWidget(self.play_video)

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 321, 20))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "B7"))
        self.load_video_button.setText(_translate("MainWindow", "Load"))
        self.process_file_button.setText(_translate("MainWindow", "Process Video"))
        self.play_video.setText(_translate("MainWindow", "Play Video"))


    def open_dialog_box(self):
        qfd = QFileDialog()
        path = "."
        title = "Open Video"
        filter = "mp4(*.mp4);;avi(*.avi)"
        filename = QFileDialog.getOpenFileName(qfd, title, path, filter)
        path = filename[0]
        if (os.path.isfile(path)):
            print(path)
            self.process_file_button.setDisabled(False)
            self.video_path = path
            self.lineEdit.setText = path

    def print_path(self):
        print(self.video_path)
        if(True):
            self.play_video.setDisabled(False)

    def start_video_player(self):
        dialog = video_player_window(self)
        self.dialogs.append(dialog)
        dialog.show()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())